# Generated by Django 4.0.2 on 2022-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_forum_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
